version: "3.7"
services:

    #/
    #|--------------------------------------------------------------------------
    #| Services
    #|--------------------------------------------------------------------------
    #|
    #|
    #/

    mysql:
      image: mysql:5.7
      container_name: astrify-mysql
      volumes:
        - ./docker/data/mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: astrify
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
      ports:
       - "3306:3306"

    redis:
      image: redis:alpine
      container_name: astrify-redis
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      ports:
        - "6378:6379"
      command: >
        --requirepass secret

    nginx:
      container_name: astrify-nginx
      image: nginx:alpine
      working_dir: /var/www
      volumes:
         - ./laravel:/var/www
         - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
      - "8000:80"
      - "8001:81"

    #/
    #|--------------------------------------------------------------------------
    #| Applications
    #|--------------------------------------------------------------------------
    #|
    #|
    #/

    laravel:
      container_name: astrify-laravel
      image: local-php-fpm-mysql:latest
      environment:
       APP_MODE: api
       DB_HOST: astrify-mysql
       REDIS_HOST: astrify-redis
      working_dir: /var/www
      volumes:
       - ./laravel:/var/www

    toml:
      container_name: astrify-toml
      image: local-php-fpm-mysql:latest
      environment:
       APP_MODE: api
       DB_HOST: astrify-mysql
       REDIS_HOST: astrify-redis
      working_dir: /var/www
      volumes:
       - ./toml:/var/www
